server:
  port: 0
spring:
  application:
    name: sql-consumer-sink
  jpa:
    show-sql: true
  cloud:
    function:
      definition: sqlConsumer
    stream:
      function:
        bindings:
          sqlConsumer-in-0: input
          sqlConsumer-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}