server:
  port: 0
spring:
  application:
  cloud:
    function:
      definition: httpPullSupplier
    stream:
      function:
        bindings:
          httpPullSupplier-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}